// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace JeffPires.BacklogChatGPTAssistant
{
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string BacklogChatGPTAssistantString = "12663A67-367C-44B7-B979-35D6BF13C8D1";
        public static Guid BacklogChatGPTAssistant = new Guid(BacklogChatGPTAssistantString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        
    }
}